#!/usr/bin/env python3
"""
TrivialTier Policy Generator
Generates WireGuard configs and nftables policies from access matrix JSON
"""

import json
import sys
from typing import Dict, List, Any, Optional
from pathlib import Path


def generate_wireguard_config(
    node_name: str,
    node_info: Dict[str, Any],
    all_nodes: Dict[str, Dict[str, Any]],
    access_matrix: List[Dict[str, Any]],
    private_keys: Optional[Dict[str, str]] = None
) -> str:
    """
    Generate WireGuard configuration for a specific node.
    
    Args:
        node_name: Name of the node
        node_info: Node configuration (internal_ip, public_key, listen_port, endpoint)
        all_nodes: Dictionary of all nodes
        access_matrix: List of access rules
        private_keys: Optional dictionary mapping node names to private keys
    
    Returns:
        WireGuard configuration as string
    """
    config = f"[Interface]\n"
    config += f"# Node: {node_name}\n"
    config += f"Address = {node_info['internal_ip']}/32\n"
    config += f"ListenPort = {node_info['listen_port']}\n"
    
    # Add private key if provided
    if private_keys and node_name in private_keys:
        config += f"PrivateKey = {private_keys[node_name]}\n"
    else:
        config += f"# PrivateKey = <PRIVATE_KEY_OF_{node_name.upper()}>\n"
    config += f"\n"
    
    # Add peers based on access matrix
    # For WireGuard bidirectional communication:
    # 1. If this node (source) connects to destination, add destination as peer with endpoint
    # 2. If another node (source) connects to this node (destination), add source as peer without endpoint
    peers_added = set()
    
    for rule in access_matrix:
        source = rule['source']
        destination = rule['destination']
        connectivity = rule.get('connectivity', False)
        
        if not connectivity:
            continue
            
        # Case 1: This node is the source, add destination as peer (with endpoint)
        if source == node_name and destination in all_nodes:
            if destination not in peers_added:
                peer_info = all_nodes[destination]
                config += f"[Peer]\n"
                config += f"# Peer: {destination} (outbound connection)\n"
                config += f"PublicKey = {peer_info['public_key']}\n"
                config += f"Endpoint = {peer_info['endpoint']}\n"
                config += f"AllowedIPs = {peer_info['internal_ip']}/32\n"
                config += f"\n"
                peers_added.add(destination)
        
        # Case 2: This node is the destination, add source as peer (without endpoint for incoming)
        elif destination == node_name and source in all_nodes:
            if source not in peers_added:
                peer_info = all_nodes[source]
                config += f"[Peer]\n"
                config += f"# Peer: {source} (inbound connection - for decryption and reply)\n"
                config += f"PublicKey = {peer_info['public_key']}\n"
                config += f"# Endpoint not needed for incoming connections\n"
                config += f"AllowedIPs = {peer_info['internal_ip']}/32\n"
                config += f"\n"
                peers_added.add(source)
    
    return config


def generate_nftables_policy(
    node_name: str,
    node_info: Dict[str, Any],
    all_nodes: Dict[str, Dict[str, Any]],
    access_matrix: List[Dict[str, Any]]
) -> str:
    """
    Generate nftables policy for a specific node.
    
    Args:
        node_name: Name of the node
        node_info: Node configuration
        all_nodes: Dictionary of all nodes
        access_matrix: List of access rules
    
    Returns:
        nftables configuration as string
    """
    policy = f"# nftables policy for node: {node_name}\n"
    policy += f"# Generated by TrivialTier Policy Generator\n"
    policy += f"# Note: Rules filter traffic by source IP from WireGuard network\n"
    policy += f"# You may want to add interface filtering (e.g., iifname \"wg0\") for tighter control\n\n"
    
    # Flush existing table to avoid conflicts
    policy += f"# Flush existing table (if exists)\n"
    policy += f"nft flush table inet wireguard_policy 2>/dev/null || true\n"
    policy += f"nft delete table inet wireguard_policy 2>/dev/null || true\n\n"
    
    policy += f"table inet wireguard_policy {{\n"
    policy += f"    chain input {{\n"
    policy += f"        type filter hook input priority filter; policy drop;\n"
    policy += f"        # Allow loopback\n"
    policy += f"        iif lo accept\n"
    policy += f"        # Allow established and related connections\n"
    policy += f"        ct state established,related accept\n"
    policy += f"\n"
    
    # Process rules where this node is the destination
    for rule in access_matrix:
        source = rule['source']
        destination = rule['destination']
        connectivity = rule.get('connectivity', False)
        l4_rules = rule.get('l4_rules', [])
        
        if destination == node_name and connectivity and source in all_nodes:
            source_ip = all_nodes[source]['internal_ip']
            
            for l4_rule in l4_rules:
                proto = l4_rule.get('proto', '').lower()
                action = l4_rule.get('action', 'accept').lower()
                
                if proto == 'icmp':
                    policy += f"        # Allow ICMP from {source} ({source_ip})\n"
                    policy += f"        ip saddr {source_ip} icmp type echo-request {action}\n"
                    policy += f"        ip saddr {source_ip} icmp type echo-reply {action}\n"
                elif proto == 'tcp':
                    ports = l4_rule.get('ports', [])
                    if ports:
                        ports_str = ','.join(map(str, ports))
                        policy += f"        # Allow TCP ports {ports_str} from {source} ({source_ip})\n"
                        policy += f"        ip saddr {source_ip} tcp dport {{ {ports_str} }} {action}\n"
                    else:
                        policy += f"        # Allow all TCP from {source} ({source_ip})\n"
                        policy += f"        ip saddr {source_ip} tcp {action}\n"
                elif proto == 'udp':
                    ports = l4_rule.get('ports', [])
                    if ports:
                        ports_str = ','.join(map(str, ports))
                        policy += f"        # Allow UDP ports {ports_str} from {source} ({source_ip})\n"
                        policy += f"        ip saddr {source_ip} udp dport {{ {ports_str} }} {action}\n"
                    else:
                        policy += f"        # Allow all UDP from {source} ({source_ip})\n"
                        policy += f"        ip saddr {source_ip} udp {action}\n"
            
            policy += f"\n"
    
    policy += f"        # Default drop (already set by policy)\n"
    policy += f"    }}\n"
    policy += f"\n"
    
    # Output chain for outbound traffic
    policy += f"    chain output {{\n"
    policy += f"        type filter hook output priority filter; policy accept;\n"
    policy += f"        # Allow all outbound traffic\n"
    policy += f"    }}\n"
    policy += f"\n"
    
    # Forward chain (for routing if needed)
    policy += f"    chain forward {{\n"
    policy += f"        type filter hook forward priority filter; policy drop;\n"
    policy += f"        # Default drop for forwarding\n"
    policy += f"    }}\n"
    
    policy += f"}}\n"
    
    return policy


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python generator.py <input.json> [output_dir] [private_keys.json]", file=sys.stderr)
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("output")
    private_keys_file = sys.argv[3] if len(sys.argv) > 3 else None
    
    # Read input JSON
    with open(input_file, 'r') as f:
        data = json.load(f)
    
    nodes = data['nodes']
    access_matrix = data['access_matrix']
    
    # Read private keys if provided
    private_keys = None
    if private_keys_file and Path(private_keys_file).exists():
        with open(private_keys_file, 'r') as f:
            private_keys = json.load(f)
        print(f"Loaded private keys from: {private_keys_file}")
    
    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate configs for each node
    for node_name, node_info in nodes.items():
        # Generate WireGuard config
        wg_config = generate_wireguard_config(node_name, node_info, nodes, access_matrix, private_keys)
        wg_file = output_dir / f"{node_name}.conf"
        with open(wg_file, 'w') as f:
            f.write(wg_config)
        print(f"Generated WireGuard config: {wg_file}")
        
        # Generate nftables policy
        nft_policy = generate_nftables_policy(node_name, node_info, nodes, access_matrix)
        nft_file = output_dir / f"{node_name}.nft"
        with open(nft_file, 'w') as f:
            f.write(nft_policy)
        print(f"Generated nftables policy: {nft_file}")


if __name__ == "__main__":
    main()

