[Interface]
# Node: nas_core
Address = 10.0.0.100/32
ListenPort = 51820
# PrivateKey = <PRIVATE_KEY_OF_NAS_CORE>

[Peer]
# Peer: laptop_li (inbound connection - for decryption and reply)
PublicKey = 7b5R...v1W0=
# Endpoint not needed for incoming connections
AllowedIPs = 10.0.0.2/32

[Peer]
# Peer: scu-lab-server (inbound connection - for decryption and reply)
PublicKey = peer_pubkey_A
# Endpoint not needed for incoming connections
AllowedIPs = 10.0.0.1/32

